# Generated by Django 5.1.3 on 2024-11-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.TextField()),
                ('email', models.EmailField(max_length=320)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
