# Generated by Django 5.1.3 on 2024-11-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='limite_emprestimos',
            field=models.IntegerField(default=3),
        ),
    ]
