# Generated by Django 5.1.3 on 2024-11-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_livro_disponivel_alter_livro_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
    ]
