# Generated by Django 5.1.3 on 2024-11-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_remove_livro_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
